name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install --upgrade pip | pip install -r requirements.txt
    runs-on: ubuntu-latest
    container: python:3.9-slim
