name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    steps:
      name: Checkout
      uses: actions/checkout@v3
    runs-on: ubuntu-latest
    container: python:3.9-slim
